spring.application.name=embeddings-java-sqlite
spring.datasource.url=jdbc:sqlite:user_messages.db
spring.datasource.driver-class-name=org.sqlite.JDBC
spring.datasource.hikari.maximum-pool-size=1

server.port=8080

app.embedding.model-directory=.models/paraphrase-multilingual-MiniLM-L12-v2
